### ISSUE TITLE
GeniusLociForDynamo failed installation on Revit 2020.2

### ISSUE THREAD

**Issue by exocet1979** [albandechasteigner/GeniusLociForDynamo#1]
Hello,
Could you help me resolve this issue? 
I'm on Revit 2020.2.
When I try to install Genius Loci from the Dynamo for Revit Package loader a pop up appear telling me that Genius Loci is using a newer Dynamo's version. If I click continue I get errors when I try to use it in a script.
The version I need is 2021.1.12

Thanks!

Revit 2020.2
Dynamo Core 2.3.0.5885
Dynamo Revit 2.3.0.8352

![Capture9](https://user-images.githubusercontent.com/12380714/112193923-a6bd8f80-8c08-11eb-9c06-8b4124b3d42e.PNG)

**Comment by albandechasteigner** [comment]
Hi Exocet,

The Genius Loci package is uploaded to the Package Manager with Dynamo 2.6 but Dynamo 2.3 is fully compatible so you can ignore the warning and install it without worry. A restart of Revit may be required after installing the package. 
Can you explain and show what the error in the graph is after installation?

NB : The best is always to install the latest version of the package.
