### ISSUE TITLE
Get Wall Member Node dosen't work on Dynamo2.13.1.3891 on Revit 2023

### ISSUE THREAD

**Issue by samubaki** [albandechasteigner/GeniusLociForDynamo#10]
Hi,

I try to use Get Wall Member Node on  revit 2023, It dosen't work

But I try on Revit 2022, it work correctly.

![image](https://user-images.githubusercontent.com/105899659/169442941-614eb798-7bee-462a-a750-d54c626ce9c1.png)

**Comment by albandechasteigner** [comment]
Hi,
Thanks for letting me know but I can't reproduce your issue.
![image](https://user-images.githubusercontent.com/67761287/169484614-f4483d15-2bea-4187-bd4d-9a2765d858c6.png)

Can you try again and if the problem persists provide me with a minimal Revit file?

**Comment by albandechasteigner** [comment]
Hi,
Be sure to have the DynamoIronPython2.7 package installed. It is needed for the Genius Loci package (and other packages with nodes in Python for Revit)
![image](https://user-images.githubusercontent.com/67761287/169545838-f272d1d2-36ac-4e31-8987-b5c3a60168c8.png)

**Comment by samubaki** [comment]
Hi,
I updated DynamoIronPytron2.7
Now It worked.

Thank you so much.
![image](https://user-images.githubusercontent.com/105899659/169663460-56633d26-2f17-42f7-afb4-ae55937efc28.png)
