### ISSUE TITLE
Dimension properties node

### ISSUE THREAD

**Issue by ThirzaBoes** [albandechasteigner/GeniusLociForDynamo#13]
Hi, i noticed that the dimension properties node only works on vertical dimensions and not horizontal dimensions am i doing something wrong or is there something in de node wrong

**Comment by albandechasteigner** [comment]
Hi,
I confirm that the Dimension Properties works normally on horizontal dimensions.

Can you illustrate the problem you are encountering with at least a graph image and preferably a project to test with the Dynamo graph (.dyn) ?
![Horizontal dim](https://user-images.githubusercontent.com/67761287/176151468-6055e7ff-1fee-4091-9e3e-140705052851.png)
