### ISSUE TITLE
Object Lineweight change

### ISSUE THREAD

**Issue by kslifter** [albandechasteigner/GeniusLociForDynamo#16]
Hello, 

I initially posted this question in the Dynamo forums, but never received an actual reply to my question. 

I put together this script and there are no errors or nulls, but nothing seemed to change in my object style settings. Are you able to tell what I am missing? 

![image](https://user-images.githubusercontent.com/91616483/201393657-7d8feaff-d6f3-462d-9000-23f9d98e78fc.png)

Thanks,

-Ian

**Comment by albandechasteigner** [comment]
Solved on Dynamo forum :
https://forum.dynamobim.com/t/updating-object-style-line-weights/82973/13
