### ISSUE TITLE
Export IFC in Document problem in Revit 2023

### ISSUE THREAD

**Issue by mlohden** [albandechasteigner/GeniusLociForDynamo#17]
I have a Dynamo graph/script (see attached screenshot) using your Export IFC in Document node that works in Revit 2022 but returns a null value when I try it in 2023. Has there been a change in 2023 in the IFC export function? Perhaps there is a simple fix in the Python code?

Any guidance you can provide is much appreciated. 

![2022-12-02_09-25-30](https://user-images.githubusercontent.com/37819230/205350368-5f309c87-4270-4c3c-91cd-a67d9f0b7aa6.jpg)

**Comment by albandechasteigner** [comment]
Hi,

With the latest updates of the Rhythm package, you need to convert the Dynamo Document to an "API" document (_ʳʰʸᵗʰᵐ|Documents.DynamoDocumentToDbDocument_ node).
The IFC Version must also be
![Export IFC](https://user-images.githubusercontent.com/67761287/205443142-78e55aff-6c85-4185-8c67-a034b632f71f.png)
 written _IFC2x3.
