### ISSUE TITLE
Open-sourcing GeniusLoci

### ISSUE THREAD

**Issue by stgeorges** [albandechasteigner/GeniusLociForDynamo#18]
Hi @albandechasteigner ,
I see the _GeniusLociForDynamo/py_ folder contains source code for only one file: "Element Inner Centroid.py".
Are you planning on open-sourcing the GeniusLoci plugin?

**Comment by albandechasteigner** [comment]
Hi,
In fact, the codes are already available in the Nodes folder. They are on the other hand in json format which complicates their reading a little.
It should be possible to create a Dynamo graph that edits them and saves them to .py files.

**Comment by stgeorges** [comment]
Hi @albandechasteigner ,
Thank you for the quick reply. I was not aware of this!
Thank you again.
