### ISSUE TITLE
Curves FromHatch

### ISSUE THREAD

**Issue by boiiinng** [albandechasteigner/GeniusLociForDynamo#19]
I am getting a null response when using this node even though the cad link has hatches in it.  Is there something I need to do to the hatches in the CAD file?

**Comment by albandechasteigner** [comment]
Hi, 
Can you had a picture of your graph, your Dynamo graph and your cad link to this topic ?
There can be multiple causes and to provide accurate help I need more information.

**Comment by boiiinng** [comment]
I've attached the graph, and a couple dummy files.  The DWG has just one rectangle and a hatch pattern.  It is linked into the Revit file in a drafting view.
[CADHatchImport.zip](https://github.com/albandechasteigner/GeniusLociForDynamo/files/10460965/CADHatchImport.zip)

**Comment by albandechasteigner** [comment]
Hi,
Thanks for the report of this behaviour and for the files.
The custom node did not work with item lists. You can use the longest lacing or replace it with the updated node :  https://github.com/albandechasteigner/GeniusLociForDynamo/blob/master/Nodes/Curves%20FromHatch.dyf
![CADHatchImport2](https://user-images.githubusercontent.com/67761287/213663669-44eee7d3-7ed6-4754-a403-1b4ecb994dc8.png)
[CADHatchImport v2.zip](https://github.com/albandechasteigner/GeniusLociForDynamo/files/10465099/CADHatchImport.v2.zip)

**Comment by boiiinng** [comment]
I replaced the dyf file but it's saying "Error: Custom node definition is not loaded!"

**Comment by albandechasteigner** [comment]
Hi,
You need to click the Raw button and right click save as to properly download the custom node.
I updated the package (now **version 2023.1.23**) which will eliminate node replacement. The updated node now works with list of items.
