### ISSUE TITLE
Import DWG Issue

### ISSUE THREAD

**Issue by plmkonji** [albandechasteigner/GeniusLociForDynamo#2]
I apologize if this is not the correct place to post this.

I am using the Import DWG node and would like to be able to get the 3D autocad imports to show up in all views of the Revit family file. Currently there is only an option to specify a single view. If not possible, are there any alternative solutions?

Thank you and great package!

**Comment by albandechasteigner** [comment]
Hi,
I'm glad you found the package useful.
You will find the updated _Import Dwg_ node in the _Genius Loci_ package version 2021.6.3.
![import DWG](https://user-images.githubusercontent.com/67761287/120664021-dd2a4d00-c48a-11eb-93c9-d41368519847.png)

**Comment by plmkonji** [comment]
Thank you very much!

**Comment by plmkonji** [comment]
Hey Alban,

Is it possible to specify in the Import DWG node what Revit drawing the CAD is being imported into? I'm trying to run a batch process and the script isn't working correctly. I'm using the Background.Open node from the Orchid package to open several Revit families and would like to import a different CAD drawing into each based on the same name of the file.

![image](https://user-images.githubusercontent.com/85272638/120691721-aa1c9500-c45b-11eb-80d4-240e9da31b16.png)

**Comment by albandechasteigner** [comment]
Hi,
This is not currently possible. This requires an input Document as for the _Export DWG_ node. 
![export](https://user-images.githubusercontent.com/67761287/120694428-774dbd80-c4aa-11eb-892c-f2b2e2c49f3a.png)

For your information, Orchid Documents aren't compatible with other custom nodes, unlike the _Applications.OpenDocumentFile_ node of Rhythm package. 

Your workflow is very specific so unfortunately I can't spend time modifying the script and adding the Document input only for you. 
Cheers,

**Comment by plmkonji** [comment]
No problem and I understand, thanks for the quick response!
