### ISSUE TITLE
Compound Surface Reference Node

### ISSUE THREAD

**Issue by seanspence78** [albandechasteigner/GeniusLociForDynamo#20]
I was just using your "Compound Surface Reference Node" and noticed that the bottom surface was reporting material and the material was reporting the surface
![Compound Surface Reference](https://user-images.githubusercontent.com/25461614/213543230-67234deb-2caa-40d0-a8f4-48e03c8c6cb7.jpg)

**Comment by albandechasteigner** [comment]
Hi Sean, 
Thanks for the coffee and for pointing out this reversal of two outputs. 
I fixed the node and will attach it to the next package update. In the meantime it can be [downloaded ](https://github.com/albandechasteigner/GeniusLociForDynamo/blob/master/Nodes/Compound%20Surfaces%20References.dyf) and the old node replaced in C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\2.16\packages\Genius Loci\dyf

**Comment by albandechasteigner** [comment]
Fixed in package version 2023.1.23.
