### ISSUE TITLE
node Get ColorFill Scheme Properties unable to return values for AreaScheme

### ISSUE THREAD

**Issue by chartreuseUNICORN** [albandechasteigner/GeniusLociForDynamo#22]
the python script in this node seems to fail to find the correct BIP associated with the ColorFillScheme's ParameterDefinition when the ParameterDefinition is a ParameterElement and not a BIP integer.  Not really sure if the second case for identifying the paramName values is supposed to cover this.  Maybe a third case needs to be implemented and have the parameter collection be moved into the try/except?

**Comment by albandechasteigner** [comment]
Hi,
Thanks for your remark. Indeed, only the BIP and Shared parameters were taken into account and the project parameters were missing.
The updated node can be [donwloaded](https://github.com/albandechasteigner/GeniusLociForDynamo/blob/master/Nodes/Get%20ColorFill%20Scheme%20Properties.dyf) and the old node replaced in C:\Users\\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\2.16\packages\Genius Loci\dyf
(You need to click the Raw button and right click save as to properly download the custom node.)
Best regards,
