### ISSUE TITLE
Material Set not working from list

### ISSUE THREAD

**Issue by frankiepb98** [albandechasteigner/GeniusLociForDynamo#23]
Hi, when I use the "Material Set Appearance Asset" it is only working for a single material. Either by a single string, or if I use the attached image and filter for a single material, it works too. But, if I filter by a name that gives me 3 materials, only the first material will be changed, and the rest will not change. Is the "Material Set Appearance Asset" written to only change a single material? Or Am I doing something wrong? Should I use a different command when I have a list of materials instead of a single material? Thanks!

![Material Set from List](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/136847126/cd304232-b3aa-4f54-bc74-8b7d603ebad2)

**Comment by albandechasteigner** [comment]
Hi,

I can't see all your graph but try with the longest lacing on the Material Set AppearanceAsset node.

**Comment by albandechasteigner** [comment]
Hi,

The lacing operation is explained on the Primer : [https://primer.dynamobim.org/06_Designing-with-Lists/6-1_whats-a-list.html](url)
See if the longest lacing solves your issue.

**Comment by frankiepb98** [comment]
Yes! It works now. Thanks! Last question, should I do something about the CPython3 message?

Thanks you!

![CPython3](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/136847126/0b7806fe-e95b-4fe4-9a5a-0264848eb96b)

**Comment by albandechasteigner** [comment]
Great. 
I don't plan to immediately migrate the 350 custom nodes from the package to the CPython engine so you can check the "Do not show again" box.
