### ISSUE TITLE
Get Filter Overrides - CutLineColor

### ISSUE THREAD

**Issue by DJBuck** [albandechasteigner/GeniusLociForDynamo#25]
Hi, apologies if this is not the correct forum to raise such issues, but when using the Get Filter Overrides node, the CutLineColor output appears to be outputting the incorrect values (doubles rather than colours). The ProjectionLineColor output is working correctly, comparison displayed in image below.

Revit 2023.1
Dynamo 2.16
GeniusLoci 2023.2.21

![image](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/48869354/62e2bc5c-1e38-4567-9c85-48c237dd80de)

**Comment by albandechasteigner** [comment]
Hi,

Thanks for reporting. Indeed the CutLineColor and CutLine Weight outputs were reversed. 
I updated the custom node in the github repository and will include the update in the next release of the package.
Best regards,
