### ISSUE TITLE
CAD Block Layers

### ISSUE THREAD

**Issue by darbinieks123** [albandechasteigner/GeniusLociForDynamo#26]
Hello
While using CAD Block some block layers are "null"
![image](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/143614252/7f8250d4-53c2-4057-a209-2dfe06de3414)
In my case "null" are only block "LAPUKO" other blocks in the same Layer shows up correctly
i checked in .dwg there everything looks fine
![image](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/143614252/f57d7a0e-0a5b-4771-9dae-7cfde17b2684)
I am using Revit 2024

**Comment by albandechasteigner** [comment]
Hi,

It is not possible to find the reason of this issue and help you without the DWG. 
Maybe "LAPUKO" blocks contain nested blocks?

Best regards,
