### ISSUE TITLE
View CropBox does not handle ViewType.Detail

### ISSUE THREAD

**Issue by jake1108** [albandechasteigner/GeniusLociForDynamo#28]
I just discovered that within the View CropBox node, that it could not handle my detail views. 

Upon investigation it seems that the node does not have a condition to catch views of the type ViewType.Detail. 

The three conditions are:
`if view.ViewType == ViewType.FloorPlan or view.ViewType == ViewType.CeilingPlan or view.ViewType == ViewType.EngineeringPlan :`
`elif view.ViewType == ViewType.Section or view.ViewType == ViewType.Elevation :`
`elif view.ViewType == ViewType.ThreeD:`

I added `or view.ViewType == ViewType.Detail:` to row 58 and the node works.

**Comment by albandechasteigner** [comment]
Hi Jake,

Thanks for adding. 
I will publish an update to the package.
