### ISSUE TITLE
Custom Nodes - Can't Find

### ISSUE THREAD

**Issue by JMayesSteelhead** [albandechasteigner/GeniusLociForDynamo#3]
Hi. My boss sent me and image of Dynamo script he uses and I'm trying to recreate it with your package. But I can't find the nodes he's using: 
GeniusLoci.Family Document   and   GeniusLoci.FamilyDocument Parameters
He's using 2020.12.22 but I don't see both of these nodes in that version. Which version has both of these nodes available?
![MicrosoftTeams-image](https://user-images.githubusercontent.com/87538398/125974067-4f92fd12-bf00-4d29-9ff2-ad984cff9624.png)

**Comment by albandechasteigner** [comment]
Hi,

The easiest way is to use the latest version of the package and you will find these nodes. I don't remember which version of the package they were added to. 
Don't use the GeniusLoci prefix to find them in the library. 
![Family](https://user-images.githubusercontent.com/67761287/125976477-2c719ed4-b22e-4c40-8a07-5a136244f45c.png)
