### ISSUE TITLE
Export IFC - IFC Site

### ISSUE THREAD

**Issue by RomualdND** [albandechasteigner/GeniusLociForDynamo#30]
Hello 

I use your IFC Export node, is it possible to manage the IFCsite elevation in the advanced settings?

Thank you for your reply

**Comment by albandechasteigner** [comment]
Hi Romuald,

There is already a dedicated line in the custom node.
![Export IFC](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/67761287/95f6535f-db9e-4a3c-81be-edfc6fe3a891)

You can set the value to false if necessary.
