### ISSUE TITLE
Document Units for Revit links

### ISSUE THREAD

**Issue by Acastillo-eus** [albandechasteigner/GeniusLociForDynamo#31]
I'm trying to have the units in use for all the linked models and the node will output the units of the open document and not the links.
I've tested linking 2 models, with length units one in inches and other in cm to the open model in meters and the result is meters for both of them. I'm using Revit 2023.1 and DYNAMO v.2.16.1 

![imagen](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/123563975/64f3af74-c7e1-4b72-a5df-0d9c855c699e)

**Comment by albandechasteigner** [comment]
Hi,

Thank you for your comment. I have now fixed the custom node and will publish an update to the package.
![doc units](https://github.com/albandechasteigner/GeniusLociForDynamo/assets/67761287/d7d8f182-9e79-4ed2-835a-6f54eed238bf)

**Comment by Acastillo-eus** [comment]
Thank you Alban!
