### ISSUE TITLE
View ToSheet method depreciated in R23+

### ISSUE THREAD

**Issue by jake1108** [albandechasteigner/GeniusLociForDynamo#32]
Hi Alban,

The View ToSheet node was not returning anything for me in R24.2. 

Upon investigation, the case-sensitive version of the method you deploy to filter sheet numbers was removed in R23.

https://www.revitapidocs.com/2022/056fd8e1-a989-b262-8c8e-9e79ece62b01.htm. 

The non-case-sensitive version of this method is still valid (https://www.revitapidocs.com/2022/5bd5286a-612f-e12f-e200-6a8763bb2aee.htm), so simply removing the boolean parameter from line 17 means the code still works as expected.
`fRule = FilterStringRule(pvp, fsr, sheetNumber)`

Jake

**Comment by albandechasteigner** [comment]
Hi Jake,

Thanks for the investigation, explanations and fix.
The fix is ​​part of the new version 2024.2.10 of the _Genius Loci_ package.

Best regards,
alban
