### ISSUE TITLE
Nearest Building Story (Nearest Level.dyf)

### ISSUE THREAD

**Issue by MennoMekes** [albandechasteigner/GeniusLociForDynamo#33]
Hi, 

Is it possible to add an input that let's you in-, or exclude Levels that are not a Building Story?

**Comment by albandechasteigner** [comment]
Hi,

The method used comes from the Revit API and doesn't offer the possibility of excluding levels which are not Building storey.
But it is possible to achieve the same result with a few lines of codes :
var levels = new FilteredElementCollector(m_doc).OfClass(typeof(Level)).Cast<Level>().Where(x => x.get_Parameter(BuiltInParameter.LEVEL_IS_BUILDING_STORY) != null).OrderByDescending(lev => lev.ProjectElevation).ToList()
rest of the logic ...

**Comment by MennoMekes** [comment]
Thanks!
