### ISSUE TITLE
GeniusLoci.Utilities.List SortNatural: Unexpected behaviour encountered

### ISSUE THREAD

**Issue by andreasmweber** [albandechasteigner/GeniusLociForDynamo#35]
Hello Alban, 
Thank you first of all for your fantastic work and your contribution to Dynamo packages. I have encountered an unexpected behaviour when using the List.SortNatural-Node in a Dynamo graph as shown in the two screenshots. 

![2024-07-28_Line Pattern_01](https://github.com/user-attachments/assets/cc4f077f-c3de-4fd3-bacf-bde60b580334)

The red box indicates the only difference in the nodes of the two versions. In the second screenshot, alphabetical sorting works fine, but the filter after rearranging the list is leading to a  completely different and unwanted result.

![2024-07-28_Line Pattern_02](https://github.com/user-attachments/assets/d1106334-9799-4f42-b9a5-978de8d72d6c)

Is this behaviour intended?
I am using Revit 2023.1 and DYNAMO v.2.16.2 with GeniusLoci 2023.7.13

**Comment by albandechasteigner** [comment]
Hi @andreasmweber,

Thanks for your kinds words.
I can see a flaw in the logic used. You use the FilterByBoolMask node on the unsorted list. 
Instead, connect it to the List Sort Natural node.
![Sort](https://github.com/user-attachments/assets/58e04cc0-4c1e-402b-9394-b1930418b2a1)
