### ISSUE TITLE
Dimension ByReferences

### ISSUE THREAD

**Issue by Kershoek** [albandechasteigner/GeniusLociForDynamo#36]
Hello,

im running a script using the Dimension ByReferences block, but it works fine in 2022...but not in 2023 for some reason.
I did install the DynamoIronPython2.7 package as described.
result i am getting is the correct amount of output/results from the block, but they come out as Null...and not as actual dimensions.
Any idea what this could be? 
![dynamo dimension error](https://github.com/user-attachments/assets/9f350e1d-cf4a-4f05-9f6c-a5c68612b7ea)

**Comment by albandechasteigner** [comment]
Hi @Kershoek,

Is it indeed version **2.5** of the DynamoIronPython2.7 package that is installed in Revit 2023?
![image](https://github.com/user-attachments/assets/d0c45e91-a9a8-45c3-af66-f8c005b1fc95)

Other versions of the package are for Dynamo 3.x

Best regards,

**Comment by Kershoek** [comment]
yes it is 2.5
![image](https://github.com/user-attachments/assets/07679678-6fce-4ac3-ac8c-eecda71d55a5)

**Comment by Kershoek** [comment]
i could... but i am not really able to minimize the model below the allowed 25MB here.

**Comment by albandechasteigner** [comment]
You can use a file transfer service (wetransfer, fromsmash...) to share your model.

**Comment by Kershoek** [comment]
i have send a wetransfer to your email geniusloci.bim

**Comment by albandechasteigner** [comment]
I can't get your graph that has hundreds of nodes and a user interface to work. 
In any case, with a very reduced test version, the Dimension ByReferences node works as expected in Revit 2023.
![Test Revit 2023](https://github.com/user-attachments/assets/37a0b2b8-2bde-4331-9f6f-89809b16b7c7)
[Test dimension.zip](https://github.com/user-attachments/files/16873525/Test.dimension.zip)

**Comment by Kershoek** [comment]
It doesnt work on my PC. I guess there is still something wrong with the packages that i have installed??
i am not sure if i should install the newer version of the Geniusloci package as Dynamo suggests?
![image](https://github.com/user-attachments/assets/43a642ee-ab52-46bf-a8f5-eaf8eb3dfa81)

**Comment by albandechasteigner** [comment]
Hi,

You can install the latest version of the package. It is working with Revit 2022, 2023 and 2024.

**Comment by Kershoek** [comment]
it looks like i just needed to update the packages..... i am so sorry to have wasted your time on this... i thought the packages where updated, but they where not. 
But that does raise a question on something i never understood... 
We have our packages installed on our sentral server. Everybody assigns that folder to the packages path in their revit. Every Revit version with their own packages folder with the right versions to prevent problems like we had now. BUT... somehow... even if they have assigned the right folder... i still need to install the right package on every machine in order for it to work. Can you explain how this works? its probably something simple, but i have never gotten my head arround on how it works with packages and how and where to install them properly. i guess we have been lucky so far that it just worked.

**Comment by albandechasteigner** [comment]
Hosting all packages on a central server is not recommended by Autodesk. This can cause delays and accessibility conflicts if several people work on Dyanmo at the same time. 
It is better to favor a mechanism for copying packages hosted on your server to the hard drive of the local computers or to use a cloud solution like https://orkestra.online/

**Comment by Kershoek** [comment]
we are using Sharepoint so everything is synchronised to the local machines anyway.... but i will look into orkestra and see if this improves our workflow. 
Thank you very much for your time and advice.
Regards,
Erik.
