### ISSUE TITLE
Greeetings Alban! Issue with Geniu Loci package installation failure

### ISSUE THREAD

**Issue by Mikedado** [albandechasteigner/GeniusLociForDynamo#37]
Greetings! I´m writing because with Autodesk Revit 2022 when i try to download and install the Genius Loci package 2022.1.5 within Dyanmo i receive the error message attached : 
![INC0319006 genius loci update failure](https://github.com/user-attachments/assets/7a7dfcc7-f264-4c74-9be7-88b64b56b24f)

Not sure what i´m doing wrong, any suggestions would be greatly appreciated.

PS: The error message says : "Access path name can´t be an empty value".
Thanks in advance 
Mike

**Comment by albandechasteigner** [comment]
Hi Mike,

I advise you to install the most recent version (2024.5.29) of the package. It will also work with Revit 2022. 
For the error, you can download the package at [](https://dynamopackages.com) and unzip the content in C:\Users\%USERNAME%\AppData\Roaming\Dynamo\Dynamo Revit\2.12\packages\Genius Loci

Best regards,
Alban
