### ISSUE TITLE
Element SetRotation.dyf Section Box rotation

### ISSUE THREAD

**Issue by truevis** [albandechasteigner/GeniusLociForDynamo#4]
It doesn’t seem to rotate a Section Box around its center.
![image](https://user-images.githubusercontent.com/3574046/126023722-97985dc3-3f0f-489e-b719-02dccc2dc4c5.png)
![image](https://user-images.githubusercontent.com/3574046/126023712-b19b70b6-3e75-4a60-b7d6-1fb6c360b381.png)
![image](https://user-images.githubusercontent.com/3574046/126023718-2a87e986-c896-4ed5-8215-9c7ac7fc799e.png)

**Comment by albandechasteigner** [comment]
Hi,
Thanks for reporting this issue.
I've updated the Element SetRotation node. You can download the updated .dyf custom node or wait for an update of the package.
Cheers,
