### ISSUE TITLE
Create Materials Node Stops running past first material on a list pulling from excel

### ISSUE THREAD

**Issue by gruizking** [albandechasteigner/GeniusLociForDynamo#5]
The graph below is what I've put together to the create materials node at the end to pull values from the excel in order to automate create the list of materials.
![Create Materials_210804_2021-08-06_03-16-52](https://user-images.githubusercontent.com/88557888/128560925-119af2ac-5b2a-45fc-933f-d46b9b79fc13.png)

**Comment by gruizking** [comment]
Solved the issue. The node says graphic options are optional but they are not. Once I had all the options with the proper inputs it ran through the full list of almost 100 materials.

**Comment by albandechasteigner** [comment]
Hi @gruizking,

Graphics inputs are really optional. You just have to use longest lacing in this specific case.
![image](https://user-images.githubusercontent.com/67761287/129728161-ca9968bc-9cb6-4f90-b12f-f693a85d456d.png)
