### ISSUE TITLE
Appearance Asset Nodes Returning Null

### ISSUE THREAD

**Issue by jdrachenberg** [albandechasteigner/GeniusLociForDynamo#9]
Hello,

I am starting work on a script to pull material data from a Revit project to excel, modify data in excel, then re-create new materials with that data in a new Revit file.

I just started working with Genius Loci, and the AppearanceAsset nodes are returning null values. Could someone let me know what might be causing this? I am running Genius Loci 2022.3.9 in Dynamo Core 2.10.1.3976, Dynamo Revit 2.10.1.4002.

![image](https://user-images.githubusercontent.com/101476337/158031692-4f980804-59a0-4f92-af7d-efec9b3f3912.png)

Thanks,

Jonathan

**Comment by albandechasteigner** [comment]
Hi Jonathan,
Can you try with another AppearanceAssetElement, the second or the third ? Or can you share your Revit file ?
It is working fine for me with Revit 2022.
Best regards,
Alban
![image](https://user-images.githubusercontent.com/67761287/158347124-4e3c4145-9624-4ae6-8b47-5f2d5406baac.png)

**Comment by jdrachenberg** [comment]
Hi Alban,

I tried with another appearance asset, but no success. I also tried uninstalling and reinstalling Revit 2022 - again, no change.

The only difference I see is yours is running in Dynamo Revit 2.12, while mine is in 2.10. But it says my Dynamo version is up-to-date, and I'm having trouble finding where I can download Dynamo Revit 2.12. Dynamo Core 2.12 is available on the Dynamo website - not sure if Dynamo Revit comes along with it?
![image](https://user-images.githubusercontent.com/101476337/159105295-5c4fd3c7-bc27-479d-99dd-f8d4e6e8f45f.png)

Here's a download link for a Revit file, but it's just an empty file from an out of the box template. I've tried with several different Revit files and there aren't any changes. https://we.tl/t-YdfdCi5s4i

Regards,

Jonathan

**Comment by albandechasteigner** [comment]
Hi,
Your Revit file is working fine for me :
![image](https://user-images.githubusercontent.com/67761287/160164321-fc368436-c5fd-4995-aee9-43b263740c5f.png)

To upgrade Dynamo, you must install the latest Revit update. (currently 2022.1.2)

**Comment by jdrachenberg** [comment]
I updated Revit to 2022.1.2 and GeniusLoci works fine now. Thanks for your help, much appreciated.
